name: CI Maven Test

on:
  pull_request:
    branches:
      - main  # Trigger when a PR targets the 'main' branch
    types:
      - opened        # Trigger when a PR is opened
      - synchronize  # Trigger when a PR is updated (e.g., commits pushed)
      - reopened     # Trigger when a PR is reopened

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run tests with Maven
      run: mvn test
