name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Run JaCoCo coverage
      run: mvn jacoco:report

    - name: Check code coverage
      run: |
        COVERAGE=$(mvn jacoco:report | grep -oP 'Total.*?(\d+\.\d+)%' | tail -1 | grep -oP '\d+\.\d+')
        if (( $(echo "$COVERAGE < 80.0" | bc -l) )); then
          echo "Code coverage is below 80%"
          exit 1
        fi

    - name: Deploy to GitHub Packages
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
