name: CI

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Tests
      run: mvn test

    - name: Run JaCoCo Coverage Report
      run: mvn jacoco:report

    - name: Enforce Coverage Threshold
      run: |
        COVERAGE=$(mvn jacoco:report | grep -oP 'Total.*\K[\d.]+(?=%)')
        if (( $(echo "$COVERAGE < 80" | bc -l) )); then
          echo "Code coverage ($COVERAGE%) is below the threshold of 80%."
          exit 1
        fi

    - name: Publish to GitHub Packages Apache Maven
      if: success()
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
