name: CI/CD Maven Deploy

on:
  push:
    branches:
      - main
      - zodecky/feature/add-cd
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Maven test
      run: mvn test

    - name: Check code coverage
      run: mvn verify

    - name: Build & Deploy with Maven
      if: success() && steps.check-code-coverage.outcome == 'success'
      run: mvn deploy -s $GITHUB_WORKSPACE/.github/settings.xml
      env:
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
